version: '3.5'

services:
  vpay.ols.processor.api:
    image: ${DOCKER_REGISTRY-}vpayolsprocessorapi
    container_name: ols-processor-api
    volumes:
      - ./db-data/SRVFS:/SRVFS
    build:
      context: .
      dockerfile: src/VPay.Ols.Processor.Api/Dockerfile

  ols-sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: ols-sqlserver
    ports:
      - "5633:1433"
    command: /bin/bash -c "./entrypoint.sh"
    environment:
      SA_PASSWORD: "Your_password123"
      DATABASE_NAME: "SE_OLS"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "True"
    volumes:
      - ./db-data/data:/var/opt/mssql/data
      - ./scripts/start-sql-db/SqlCmdStartup.sh:/SqlCmdStartup.sh
      - ./scripts/start-sql-db/entrypoint.sh:/entrypoint.sh

  ols-migrate:
    image: plinfharbor.vpayusa.net/base-images/dotnet/sdk:6.0-focal
    depends_on:
      - ols-sqlserver
    volumes:
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
      - ./db-data/dbmigration/obj:/src/database/VPay.Ols.Processor.Database.Build/obj
      - ./db-data/dbmigration/bin:/src/database/VPay.Ols.Processor.Database.Build/bin
      - ./src/database:/src/database
    container_name: ols-migrate
    command: /bin/bash -c 'dotnet clean /src/database/VPay.Ols.Processor.Database.Build/VPay.Ols.Processor.Database.Build.csproj && dotnet build /src/database/VPay.Ols.Processor.Database.Build/VPay.Ols.Processor.Database.Build.csproj && dotnet publish /src/database/VPay.Ols.Processor.Database.Build/VPay.Ols.Processor.Database.Build.csproj /p:TargetUser=sa /p:TargetPassword=Your_password123 /p:TargetServerName=ols-sqlserver /p:TargetDatabaseName=SE_OLS'
    entrypoint: /wait-for-it.sh "ols-sqlserver:1433" --timeout=120 --
  
  vpay.ols.processor.queueconsumers:
    image: ${DOCKER_REGISTRY-}vpayolsprocessorqueueconsumers
    container_name: ols-processor-queueconsumers
    volumes:
      - ./db-data/SRVFS:/SRVFS
    build:
      context: .
      dockerfile: src/VPay.Ols.Processor.QueueConsumers/Dockerfile
    depends_on:
      - ols-processor-rabbitmq
   
  ols-processor-rabbitmq:
    image: rabbitmq:3.7-management
    hostname: ols-processor-rabbitmq
    container_name: ols-processor-rabbitmq
    ports:      
      - 15680:15672
    volumes:
      - ./db-data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@ols-processor-rabbitmq:cached
      - ./nacha_definitions.json:/etc/rabbitmq/definitions/nacha_definitions.json
    environment:
      RABBITMQ_ERLANG_COOKIE: "6085SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions '/etc/rabbitmq/definitions/'"