version: '3.5'

services:
  vpay.ols.processor.api:
    image: ${DOCKER_REGISTRY-}vpayolsprocessorapi
    container_name: ols-processor-api
    build:
      context: .
      dockerfile: src/VPay.Ols.Processor.Api/Dockerfile

  ols-sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: ols-sqlserver
    ports:
      - "5633:1433"
    command: /bin/bash -c "./entrypoint.sh"
    environment:
      SA_PASSWORD: "Your_password123"
      DATABASE_NAME: "OLS"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "True"
    volumes:
      - ./db-data/data:/var/opt/mssql/data
      - ./database/start-sql-db/SqlCmdStartup.sh:/SqlCmdStartup.sh
      - ./database/start-sql-db/entrypoint.sh:/entrypoint.sh

  ols-migrate:
    image: plinfharbor.vpayusa.net/base-images/dotnet/sdk:6.0-focal
    depends_on:
      - ols-sqlserver
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./db-data/dbmigration/obj:/database/VPay.Ols.Processor.Database.Build/obj
      - ./db-data/dbmigration/bin:/database/VPay.Ols.Processor.Database.Build/bin
      - ./database:/database
    container_name: ols-migrate
    command: /bin/bash -c 'dotnet clean /database/VPay.Ols.Processor.Database.Build/VPay.Ols.Processor.Database.Build.csproj && dotnet build /database/VPay.Ols.Processor.Database.Build/VPay.Ols.Processor.Database.Build.csproj && dotnet publish /database/VPay.Ols.Processor.Database.Build/VPay.Ols.Processor.Database.Build.csproj /p:TargetUser=sa /p:TargetPassword=Your_password123 /p:TargetServerName=ols-sqlserver /p:TargetDatabaseName=OLS'
    entrypoint: /wait-for-it.sh "ols-sqlserver:1433" --timeout=120 --



   
  ols-processor-rabbitmq:
    image: rabbitmq:3.7-management
    hostname: ols-processor-rabbitmq
    container_name: ols-processor-rabbitmq
    ports:      
      - 15680:15672
    volumes:
      - ./db-data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@ols-processor-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: "6085SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: / 