smbShares:
  ols-rw:
    source: '{{ vault "devops/pks/${DEPLOYMENT}/olsSmb" "source" }}'
    username: '{{ vault "devops/pks/${DEPLOYMENT}/olsSmb" "username" }}'
    password: '{{ vault "devops/pks/${DEPLOYMENT}/olsSmb" "password" }}'
  files-smb:
    username: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/smb" "username" }}'
    password: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/smb" "password" }}'

api:
  secrets:
    appsettings.secure.json:
      data:
        OlsProcessorQueue:
          username: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/rabbit" "username" }}'
          password: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/rabbit" "password" }}'
        OlsDatabase:
          Username: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLS/OLSProcessor" "username" }}'
          Password: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLS/OLSProcessor" "password" }}'
          Hostname: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLS/OLSProcessor" "hostname" }}'

queue-consumers:
  secrets:
    appsettings.secure.json:
      data:
        OlsProcessorQueue:
          username: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/rabbit" "username" }}'
          password: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/rabbit" "password" }}'
        OlsDatabase:
          Username: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLS/OLSProcessor" "username" }}'
          Password: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLS/OLSProcessor" "password" }}'
          Hostname: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLS/OLSProcessor" "hostname" }}'
        FileTransferServiceRabbitQueue:
          username: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/rabbit" "username" }}'
          password: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/rabbit" "password" }}'
    id-rsa.key:
      data: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/signing_keys" "private_key" }}'
      isEncoded: true

