smbShares:
  acctbal-rw:
    source: '{{ vault "devops/pks/${DEPLOYMENT}/acctbalSmb" "source" }}'
    username: '{{ vault "devops/pks/${DEPLOYMENT}/acctbalSmb" "username" }}'
    password: '{{ vault "devops/pks/${DEPLOYMENT}/acctbalSmb" "password" }}'

api:
  secrets:
    appsettings.secure.json:
      data:
        OlsProcessorQueue:
          username: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/processorRabbitMq" "username" }}'
          password: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/processorRabbitMq" "password" }}'
        OlsDatabase:
          Username: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/sql" "username" }}'
          Password: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/sql" "password" }}'

queue-consumers:
  secrets:
    data:
      OlsProcessorQueue:
        username: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/processorRabbitMq" "username" }}'
        password: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/processorRabbitMq" "password" }}'
      OlsDatabase:
          Username: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/sql" "username" }}'
          Password: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/sql" "password" }}'

