smbShares:
  acctbal-rw:
    source: '{{ vault "devops/pks/${DEPLOYMENT}/acctbalSmb" "source" }}'
    username: '{{ vault "devops/pks/${DEPLOYMENT}/acctbalSmb" "username" }}'
    password: '{{ vault "devops/pks/${DEPLOYMENT}/acctbalSmb" "password" }}'

api:
  secrets:
    appsettings.secure.json:
      data:
        OlsProcessorQueue:
          username: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/rabbit" "username" }}'
          password: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/rabbit" "password" }}'
        OlsDatabase:
          Username: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLSProcessor" "username" }}'
          Password: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLSProcessor" "password" }}'
          Hostname: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLSProcessor" "hostname" }}'
          Database: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLSProcessor" "database" }}'

queue-consumers:
  secrets:
    data:
      OlsProcessorQueue:
        username: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/rabbit" "username" }}'
        password: '{{ vault "engineering/ols/olsprocessor/${DEPLOYMENT}/rabbit" "password" }}'
      OlsDatabase:
          Username: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLSProcessor" "username" }}'
          Password: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLSProcessor" "password" }}'
          Hostname: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLSProcessor" "hostname" }}'
          Database: '{{ vault "dba/Accounts/Application/${DEPLOYMENT}/OLSProcessor" "database" }}'

