name: deploy-to-prod
permissions:
  actions: read
  contents: write
  id-token: write
  pull-requests: read
  security-events: write
on:
  workflow_dispatch:
    inputs:
      CHG_TICKET:
        required: true
        type: string
      WAR_ROOM:
        type: string
        default: 'false'
 
jobs:      
   deployment-production:
     uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-to-prod.yml@main
     with: 
       CHARTS_PATH: charts/ols-processor
       NAMESPACE: ols-processor-prod
       RELEASE_NAME: ols-processor
       CHG_TICKET: ${{inputs.CHG_TICKET}}
       WAR_ROOM: ${{inputs.WAR_ROOM}}
       DRYRUN: false
       PROJECT: ols-processor
      IMAGES: |
        [
          {"name": "api", "path": ".github/build-args/api/", "dockerfile": "Dockerfile", "context": "."},
          {"name": "queue-consumers", "path": ".github/build-args/queue-consumer/", "dockerfile": "Dockerfile", "context": "."}
        ]
     secrets: inherit
