name: helm-build-and-deploy-to-dev
on: [workflow_dispatch, push]

jobs:
    api:
        uses: optum-financial/vpay-actions-common-workflow/.github/workflows/docker-build-and-publish.yml@main
        with: 
            PROJECT: ols-processor 
            IMAGE_NAME: api
            BUILD_ARGS: "PROJECT_DIR PROJECT_NAME"
            DOCKER_URL: "docker.repo1.uhc.com"
            DOCKER_USERNAME: ${{ vars.PMNTS_DEVOPS_MSA }}
            DOCKER_REGISTRY_URL: "docker.repo1.uhc.com/vpay-docker"
            BUILD_ARGS_ENV_FILE_PATH: .github/build-args/api/
        secrets:
            DOCKER_PASSWORD: ${{ secrets.PMNTS_DEVOPS_MSA_PWD }} 
    queue-consumer:
        uses: optum-financial/vpay-actions-common-workflow/.github/workflows/docker-build-and-publish.yml@main
        with: 
            PROJECT: ols-processor 
            IMAGE_NAME: queue-consumers
            BUILD_ARGS: "PROJECT_DIR PROJECT_NAME"
            DOCKER_URL: "docker.repo1.uhc.com"
            DOCKER_USERNAME: ${{ vars.PMNTS_DEVOPS_MSA }}
            DOCKER_REGISTRY_URL: "docker.repo1.uhc.com/vpay-docker"
            BUILD_ARGS_ENV_FILE_PATH: .github/build-args/queue-consumer/
        secrets:
            DOCKER_PASSWORD: ${{ secrets.PMNTS_DEVOPS_MSA_PWD }}       
    deployment-plano-dev-dryrun:
        uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-plano-dev.yml@main       
        needs: [api, queue-consumer]
        with: 
            CHARTS_PATH: charts/ols-processor
            NAMESPACE: ols-processor-dev
            RELEASE_NAME: ols-processor
            DRYRUN: true
        secrets: inherit 
    deployment-stl-dev-dryrun:
        uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-stl-dev.yml@main        
        needs: [api, queue-consumer]
        with: 
            CHARTS_PATH: charts/ols-processor
            NAMESPACE: ols-processor-dev
            RELEASE_NAME: ols-processor
            DRYRUN: true
        secrets: inherit   
    deployment-plano-stage-dryrun:
        uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-plano-stage.yml@main        
        needs: [api, queue-consumer]
        with: 
            CHARTS_PATH: charts/ols-processor
            NAMESPACE: ols-processor-stage
            RELEASE_NAME: ols-processor
            DRYRUN: true
        secrets: inherit 
    deployment-stl-stage-dryrun:
         uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-stl-stage.yml@main
         needs: [api, queue-consumer]
         with: 
            CHARTS_PATH: charts/ols-processor
            NAMESPACE: ols-processor-stage 
            RELEASE_NAME: ols-processor
            DRYRUN: true
         secrets: inherit  
    # deployment-plano-production-dryrun:
    #     uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-plano-prod.yml@main
    #     with: 
    #       CHARTS_PATH: charts/ols-processor
    #       NAMESPACE: ols-processor-prod
    #       RELEASE_NAME: ols-processor
    #       DRYRUN: true
    #     secrets: inherit 
    # deployment-stl-production-dryrun:
    #     uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-stl-prod.yml@main
    #     with: 
    #       CHARTS_PATH: charts/ols-processor
    #       NAMESPACE: ols-processor-prod
    #       RELEASE_NAME: ols-processor
    #       DRYRUN: true
    #     secrets: inherit        
    deployment-plano-dev:
        uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-plano-dev.yml@main
        needs: [deployment-plano-dev-dryrun, deployment-stl-dev-dryrun]
        with: 
            CHARTS_PATH: charts/ols-processor
            NAMESPACE: ols-processor-dev
            RELEASE_NAME: ols-processor
            DRYRUN: false
        secrets: inherit
    deployment-stl-dev:
        uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-stl-dev.yml@main
        needs: [deployment-plano-dev-dryrun, deployment-stl-dev-dryrun]
        with: 
            CHARTS_PATH: charts/ols-processor
            NAMESPACE: ols-processor-dev
            RELEASE_NAME: ols-processor
            DRYRUN: false
        secrets: inherit    
